CREATE TABLE schedules
(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '작성자 식별자',
    username VARCHAR(10) NOT NULL COMMENT '작성자 이름',
    title VARCHAR(100) NOT NULL COMMENT '할 일 제목',
    contents VARCHAR(100) NOT NULL COMMENT '할 일 내용',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '생성일',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일',
    users_id BIGINT,
    CONSTRAINT fk_users_id
    FOREIGN KEY (users_id)
    REFERENCES users(id)
);


CREATE TABLE users
(
    id BIGINT NOT NULL AUTO_INCREAMENT PRIMARY KEY COMMENT '유저 식별자',
    username VARCHAR(10) NOT NULL COMMENT '유저 이름',
    email VARCHAR(20) NOT NULL UNIQUE COMMENT '유저 이메일',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '생성일',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일',
    password VARCHAR(100) NOT NULL
);